"""create invoicing tables and mill invoice fields

Revision ID: 8d1b29884ce2
Revises: 378f115e5adc
Create Date: 2026-09-09 07:45:34.426879+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d1b29884ce2"
down_revision: str | None = "378f115e5adc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buyers",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=1000), nullable=True),
        sa.Column("gstin", sa.String(length=20), nullable=True),
        sa.Column("state_name", sa.String(length=64), nullable=True),
        sa.Column("state_code", sa.String(length=4), nullable=True),
        sa.Column("cell", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buyers")),
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("hsn_sac", sa.String(length=16), nullable=True),
        sa.Column("default_gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("default_uom", sa.String(length=8), nullable=False),
        sa.Column("default_rate", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("default_gst_rate >= 0", name=op.f("ck_products_gst_rate_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_table(
        "tax_invoices",
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("invoice_number", sa.String(length=32), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'DRAFT'"), nullable=False
        ),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("buyer_id", sa.Uuid(), nullable=True),
        sa.Column("buyer_name", sa.String(length=255), nullable=False),
        sa.Column("buyer_address", sa.String(length=1000), nullable=True),
        sa.Column("buyer_gstin", sa.String(length=20), nullable=True),
        sa.Column("buyer_state_name", sa.String(length=64), nullable=True),
        sa.Column("buyer_state_code", sa.String(length=4), nullable=True),
        sa.Column("buyer_cell", sa.String(length=32), nullable=True),
        sa.Column("delivery_note", sa.String(length=64), nullable=True),
        sa.Column("mode_terms_of_payment", sa.String(length=128), nullable=True),
        sa.Column("reference_no_date", sa.String(length=128), nullable=True),
        sa.Column("other_references", sa.String(length=128), nullable=True),
        sa.Column("buyers_order_no", sa.String(length=64), nullable=True),
        sa.Column("buyers_order_dated", sa.String(length=64), nullable=True),
        sa.Column("dispatch_doc_no", sa.String(length=64), nullable=True),
        sa.Column("delivery_note_date", sa.String(length=64), nullable=True),
        sa.Column("dispatched_through", sa.String(length=128), nullable=True),
        sa.Column("destination", sa.String(length=128), nullable=True),
        sa.Column("bill_of_lading_lr_rr_no", sa.String(length=128), nullable=True),
        sa.Column("motor_vehicle_no", sa.String(length=32), nullable=True),
        sa.Column("terms_of_delivery", sa.String(length=255), nullable=True),
        sa.Column("remarks", sa.String(length=255), nullable=True),
        sa.Column("declaration", sa.String(length=1000), nullable=True),
        sa.Column("taxable_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total_tax_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("round_off", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pdf_document_id", sa.Uuid(), nullable=True),
        sa.Column("eway_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "grand_total >= 0", name=op.f("ck_tax_invoices_grand_total_non_negative")
        ),
        sa.CheckConstraint(
            "taxable_amount >= 0", name=op.f("ck_tax_invoices_taxable_non_negative")
        ),
        sa.CheckConstraint("total_tax_amount >= 0", name=op.f("ck_tax_invoices_tax_non_negative")),
        sa.ForeignKeyConstraint(
            ["buyer_id"],
            ["buyers.id"],
            name=op.f("fk_tax_invoices_buyer_id_buyers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["eway_document_id"],
            ["documents.id"],
            name=op.f("fk_tax_invoices_eway_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pdf_document_id"],
            ["documents.id"],
            name=op.f("fk_tax_invoices_pdf_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_invoices")),
        sa.UniqueConstraint("invoice_number", name=op.f("uq_tax_invoices_invoice_number")),
        sa.UniqueConstraint("reference", name=op.f("uq_tax_invoices_reference")),
    )
    op.create_index(op.f("ix_tax_invoices_buyer_id"), "tax_invoices", ["buyer_id"], unique=False)
    op.create_index(op.f("ix_tax_invoices_status"), "tax_invoices", ["status"], unique=False)
    op.create_table(
        "tax_invoice_lines",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("hsn_sac", sa.String(length=16), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("uom", sa.String(length=8), nullable=False),
        sa.Column("rate", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("taxable_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gst_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("gst_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "gst_rate >= 0", name=op.f("ck_tax_invoice_lines_line_gst_rate_non_negative")
        ),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_tax_invoice_lines_quantity_non_negative")
        ),
        sa.CheckConstraint("rate >= 0", name=op.f("ck_tax_invoice_lines_rate_non_negative")),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["tax_invoices.id"],
            name=op.f("fk_tax_invoice_lines_invoice_id_tax_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_tax_invoice_lines_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_invoice_lines")),
    )
    op.create_index(
        op.f("ix_tax_invoice_lines_invoice_id"), "tax_invoice_lines", ["invoice_id"], unique=False
    )
    op.add_column("mill_settings", sa.Column("gstin", sa.String(length=20), nullable=True))
    op.add_column("mill_settings", sa.Column("state_name", sa.String(length=64), nullable=True))
    op.add_column("mill_settings", sa.Column("state_code", sa.String(length=4), nullable=True))
    op.add_column(
        "mill_settings", sa.Column("bank_account_name", sa.String(length=255), nullable=True)
    )
    op.add_column("mill_settings", sa.Column("bank_name", sa.String(length=128), nullable=True))
    op.add_column(
        "mill_settings", sa.Column("bank_account_no", sa.String(length=64), nullable=True)
    )
    op.add_column("mill_settings", sa.Column("bank_branch", sa.String(length=128), nullable=True))
    op.add_column("mill_settings", sa.Column("bank_ifsc", sa.String(length=16), nullable=True))
    op.add_column(
        "mill_settings", sa.Column("invoice_declaration", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mill_settings", "invoice_declaration")
    op.drop_column("mill_settings", "bank_ifsc")
    op.drop_column("mill_settings", "bank_branch")
    op.drop_column("mill_settings", "bank_account_no")
    op.drop_column("mill_settings", "bank_name")
    op.drop_column("mill_settings", "bank_account_name")
    op.drop_column("mill_settings", "state_code")
    op.drop_column("mill_settings", "state_name")
    op.drop_column("mill_settings", "gstin")
    op.drop_index(op.f("ix_tax_invoice_lines_invoice_id"), table_name="tax_invoice_lines")
    op.drop_table("tax_invoice_lines")
    op.drop_index(op.f("ix_tax_invoices_status"), table_name="tax_invoices")
    op.drop_index(op.f("ix_tax_invoices_buyer_id"), table_name="tax_invoices")
    op.drop_table("tax_invoices")
    op.drop_table("products")
    op.drop_table("buyers")
    # ### end Alembic commands ###
